/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/active-deals': RouteRecordInfo<'/active-deals', '/active-deals', Record<never, never>, Record<never, never>>,
    '/analyst-corner': RouteRecordInfo<'/analyst-corner', '/analyst-corner', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/deal-details.[id]': RouteRecordInfo<'/deal-details.[id]', '/deal-details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/deals': RouteRecordInfo<'/deals', '/deals', Record<never, never>, Record<never, never>>,
    '/documents': RouteRecordInfo<'/documents', '/documents', Record<never, never>, Record<never, never>>,
    '/earnings': RouteRecordInfo<'/earnings', '/earnings', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/investors': RouteRecordInfo<'/investors', '/investors', Record<never, never>, Record<never, never>>,
    '/old-deal-details': RouteRecordInfo<'/old-deal-details', '/old-deal-details', Record<never, never>, Record<never, never>>,
    '/reporting': RouteRecordInfo<'/reporting', '/reporting', Record<never, never>, Record<never, never>>,
  }
}
